//! SeaORM entity for the `appointments` table.

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "appointments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub patient_id: Uuid,
    pub slot_id: Option<Uuid>,
    pub practitioner_id: Option<Uuid>,
    pub start_datetime: DateTimeWithTimeZone,
    pub end_datetime: DateTimeWithTimeZone,
    pub status: String,
    pub reason: Option<String>,
    pub from_waitlist_entry_id: Option<Uuid>,
    pub cancellation_reason: Option<String>,
    /// Backlink to `appointment_series.id` for occurrences generated by
    /// a recurring series (v0.9). `NULL` for singleton appointments.
    pub series_id: Option<Uuid>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
