//! SeaORM entity modules for all PAS tables.
//!
//! One entity module per table. Each module exposes:
//! - `Entity` — the entity marker type
//! - `Model` — the read struct
//! - `ActiveModel` — the write struct
//! - `Column`, `Relation`, `PrimaryKey` — generated by `DeriveEntityModel`

pub mod account;
pub mod admission;
pub mod appointment;
pub mod appointment_series;
pub mod audit_log;
pub mod bed;
pub mod bed_assignment;
pub mod charge;
pub mod consent;
pub mod coverage;
pub mod department;
pub mod discharge;
pub mod encounter;
pub mod facility;
pub mod generated_letter;
pub mod invoice;
pub mod letter_template;
pub mod outbox_dead_letter;
pub mod outbox_event;
pub mod patient;
pub mod payment;
pub mod practitioner;
pub mod practitioner_role;
pub mod referral;
pub mod room;
pub mod rtt_clock_event;
pub mod rtt_pathway;
pub mod schedule;
pub mod slot;
pub mod transfer;
pub mod waitlist_entry;
pub mod ward;
